name: Electric Bees Stock Notifications

on:
  schedule:
    # Runs every 15 minutes from 8 AM to 11 AM AEDT
    - cron: '0,15,30,45 21-23 * * *'
    # Runs every 15 minutes from 11 AM to 9 PM AEDT
    - cron: '0,15,30,45 0-9 * * *'
  workflow_dispatch:

jobs:
  check-stock:
    runs-on: ubuntu-latest
    permissions: write-all
    # Limit total job runtime to 5 minutes
    timeout-minutes: 5
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: |
        npm install
    
    - name: Check Stock Availability
      id: stock-check
      env:
        STOCK_AVAILABILITY_URLS: ${{ secrets.STOCK_AVAILABILITY_URLS }}
        PREFERRED_STORE_IDS: ${{ secrets.PREFERRED_STORE_IDS }}
        UPDATE_HASH: ${{ vars.UPDATE_HASH }}
        GH_TOKEN: ${{ secrets.PAT }}
      run: |
        node index.js
      continue-on-error: true
      
    - name: Read Results
      id: read-results
      if: ${{ steps.stock-check.outcome == 'success' }}
      run: |
        result=$(cat results.txt)
        echo "result=${result}" >> $GITHUB_OUTPUT

    - name: Send Mail
      # Only send email if previous step found new stock
      if: ${{ steps.read-results.outputs.result != '' }}
      uses: dawidd6/action-send-mail@v4
      with:
        server_address: smtp.gmail.com
        server_port: 465
        secure: true
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: New Electric Bees Stock Available
        to: ${{secrets.NOTIFICATION_EMAIL}}
        from: GitHub Actions <${{secrets.MAIL_USERNAME}}>
        html_body: |
          New stock availability detected:<br><br>---<br><br>

          ${{ fromJson(steps.read-results.outputs.result).emailBody }}
        
        # Optional priority
        priority: high

# Optimization to reduce GitHub Actions resources
env:
  # Reduce verbosity of npm logs
  NODE_OPTIONS: '--no-warnings'
  # Disable colored output to reduce log size
  NO_COLOR: '1'